### ISSUE TITLE
Can't write tests that restore projects: nuget tasks fail to cast to ITask

### ISSUE THREAD

**Issue by cdmihai** [microsoft/MSBuildSdks#138] opened 2019-11-15 22:55 UTC
In any test, on an sdk project, do `ProjectCreator.TryBuild("Restore")`. It will fail with:

```
__________________________________________________
Project "C:\Users\micodoba\AppData\Local\Temp\qp1wx2un.z2q\dirs.proj" (Restore target(s)):

Target _FilterRestoreGraphProjectInputItems:
    __________________________________________________
    Project "C:\Users\micodoba\AppData\Local\Temp\qp1wx2un.z2q\dirs.proj" is building "C:\Users\micodoba\AppData\Local\Temp\qp1wx2un.z2q\dirs.proj" (_IsProjectRestoreSupported target(s)):

    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(293,5): error MSB4127: The "WarnForInvalidProjectsTask" task could not be instantiated from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.Build.Tasks.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'NuGet.Build.Tasks.WarnForInvalidProjectsTask' to type 'Microsoft.Build.Framework.ITask'.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(293,5): error MSB4060: The "WarnForInvalidProjectsTask" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
Done building target "_FilterRestoreGraphProjectInputItems" in project "dirs.proj" -- FAILED.

Done building project "dirs.proj" -- FAILED.
```

**Comment by jeffkl** [comment] 2019-11-18 05:39
Can you try saving the project first?  I should probably make that a requirement since building in memory projects can have unintended consequences.  This worked for me:

```C#
ProjectCreator.Templates.SdkCsproj()
    .Save(Path.Combine(TestRootPath, "projectA.csproj"))
    .TryBuild("Restore", out bool result, out BuildOutput buildOutput);

result.ShouldBeTrue();
```

**Comment by cdmihai** [comment] 2019-11-18 18:42
Tried your snippet and it fails the same on my machine. So it's probably something with my machine.

**Comment by MeikTranel** [comment] 2019-11-22 20:20
You can solve the problem by adding the nuget task package:
```xml
<PackageReference Include="NuGet.Build.Tasks" Version="5.3.1" />
```
but you'll probably soon find yourself in the situation where the testrunner inside visual studio for example has already loaded the MSBuild binaries and its binding redirects from: 
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe.config`

16.3 redirects to 15.1 binaries?! how? This leads to newer sdks exploding because they use parameters in the Copy Task for example that have been added in 16.X. Using `dotnet test`
works because the msbuild.exe at the top is selected by the global.json i have put in place.

**Comment by jeffkl** [comment] 2020-05-07 16:16
I think I finally figured out the problem here.  Visual Studio Test Framework has its own NuGet.Frameworks.dll next to it!!!

```
C:\Program Files (x86)\Visual Studio 2019 Preview\Common7\IDE\Extensions\TestPlatform\NuGet.Frameworks.dll
```
![image](https://user-images.githubusercontent.com/17556515/81318138-9f1de800-9042-11ea-8247-ee30f7e1e2bc.png)

This clashes with the version that NuGet ships in box.
```
C:\Program Files (x86)\Visual Studio 2019 Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.Frameworks.dll
```
![image](https://user-images.githubusercontent.com/17556515/81318177-afce5e00-9042-11ea-8654-d185454e1001.png)

This means that when you run unit tests in Visual Studio the wrong version of NuGet.Frameworks.dll is loaded 😢 

It also happens in ReSharper because it has its own version as well!

```
%LocalAppData%\JetBrains\Installations\ReSharperPlatformVs16_45429e2e\NuGet.Frameworks.dll
```
![image](https://user-images.githubusercontent.com/17556515/81318348-f9b74400-9042-11ea-87f1-bdea279abeb3.png)

The summary is that unit tests that do in-proc builds have the wrong version of NuGet.Frameworks.dll loaded so parts of the build fail with type errors.

FYI @nkolev92

**Comment by nkolev92** [comment] 2020-05-07 21:24
Nice catch @jeffkl

I'd have expected SxS to work because the versions are different. 
Do you know why that's not happening? 

I'll reach out to test platform to understand what's going on.

**Comment by jeffkl** [comment] 2020-05-07 21:28
Good question, would the assembly binding redirect in devenv.exe.config contribute to the problem?
```xml
<dependentAssembly>
    <assemblyIdentity name="NuGet.Frameworks" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
    <codeBase version="5.7.0.0" href="c:\program files (x86)\visual studio 2019 preview\common7\ide\commonextensions\microsoft\nuget\NuGet.Frameworks.dll"/>
</dependentAssembly>

```

**Comment by nkolev92** [comment] 2020-05-07 21:31
NuGet doesn't add those binding redirects. 
I only 16.6 P5 on this machine and I don't see the bnding redirect there.

**Comment by jeffkl** [comment] 2020-05-07 21:40
Hmm okay ignore for now, I'll repro it and see exactly what's going on under the debugger

**Comment by jeffkl** [comment] 2020-05-08 16:05
I think the problem is resolved in newer versions of Visual Studio with the VSTest framework.  Its still broken in ReSharper because they're using their customer assemblies which have a different public key token.  But that's not something we can fix.  I'm closing this issue for now since I'm fixing it here: https://github.com/jeffkl/MSBuildProjectCreator/pull/49

**Closed by jeffkl** 2020-05-08 16:05 UTC
