### ISSUE TITLE
Regression CentralPackageVersions/2.0.29+ no longer works by default in projects with nuproj extension

### ISSUE THREAD

**Issue by aaronla-ms** [microsoft/MSBuildSdks#250] opened 2021-05-18 00:03 UTC
Note: the repro provided here is a minified repro from a real world use case. 

Migrating a CoreXT nuproj (not to be confused with the public package [nuget.org/nuproj](https://www.nuget.org/packages/NuProj)) project to retail toolset. To do so, we use Sdk=Microsoft.Build.NoTargets when the .nuproj is being compiled under retail toolset.

## RCA

It appears that Microsoft.Build.CentralPackageVersions is trying to detect when it's used with nuget.org/nuproj based on the project file extension. However, that's not a reliable way to detect project type.

Recommended fix: condition on the `NuProjPath` property. Note that since property order is difficult to maintain with Sdk style projects, it's probably best not to check this setting until an early build target.

## Repro Steps
1. git clone https://github.com/aaronla-ms/bug-repros.git
2. cd bug-repros\repro-cpv-regression
3. repro.cmd

## expected

both restores pass

## actual

restore under 2.0.29 and later fails, 

> $ repro
> Microsoft.Build.CentralPackageVersions/2.0.26
>   Determining projects to restore...
>   Restored C:\repos\aaronla-ms\bug-repros\repro-cpv-regression\repro-cpv-regression.nuproj (in 340 ms).
> Microsoft.Build.CentralPackageVersions/2.0.29
>   Determining projects to restore...
> C:\repos\aaronla-ms\bug-repros\repro-cpv-regression\repro-cpv-regression2.nuproj : error NU1604: Project dependency Newtonsoft.Json does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
> C:\repos\aaronla-ms\bug-repros\repro-cpv-regression\repro-cpv-regression2.nuproj : warning NU1701: Package 'Newtonsoft.Json 3.5.8' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
>   Failed to restore C:\repos\aaronla-ms\bug-repros\repro-cpv-regression\repro-cpv-regression2.nuproj (in 368 ms).
>

**Comment by jeffkl** [comment] 2021-05-18 17:10
I think [NuProj](http://nuproj.net/) has established itself as the implementation of `.nuproj` projects.  If you want your NoTargets projects to load in Visual Studio, they'll need to have a `.csproj` or `.msbuildproj` extension anyway.

I think you should do one of the following:
* Change the file extension of your projects so they load in Visual Studio and you get CentralPackageVersions
* Set `EnableCentralPackageVersions` to `true` in your project/Directory.Build.props

We can't check properties during build because a build isn't run in Visual Studio for legacy projects so everything must be set up correctly during evaluation.

**Comment by aaronla-ms** [comment] 2021-05-18 17:24
Ok. We don't really have any need to update this package for now, so I guess we'll stay on 2.0.26 for now.

**Comment by aaronla-ms** [comment] 2021-05-18 17:30
Yeah, I just confirmed that our proprietary corext/nuproj package makes reliance on project extensions as well:

>       <_NuProjProjectReference Include="@(ProjectReference)" Condition="'%(ProjectReference.Extension)' == '.nuproj' AND '%(ProjectReference.ReferenceOutputAssembly)' != 'false'" />

Will stick with 2.0.26 for now until either issue is fixed or we've moved fully to retail toolset.

**Comment by aaronla-ms** [comment] 2021-05-18 17:39
Thankfully we can override this detection. Will add this to our Directory.Build.targets before we bring in CPV:

```xml
<!-- workaround issue https://github.com/microsoft/MSBuildSdks/issues/250 -->
<PropertyGroup>
  <EnableCentralPackageVersions>true</EnableCentralPackageVersions>
</PropertyGroup>
```

**Comment by jeffkl** [comment] 2021-05-18 18:19
Closing as by design due to https://github.com/microsoft/MSBuildSdks/pull/84.  Workaround is to enable it manually or use a different file extension.

**Closed by jeffkl** 2021-05-18 18:19 UTC
Labels: wontfix
