### ISSUE TITLE
Project that should only be used to generate a nuspec using ProjectReferences do not generate dependency elements in nuspec.

### ISSUE THREAD

**Issue by AraHaan** [microsoft/MSBuildSdks#221] opened 2021-02-07 11:45 UTC
When using NoTargets to tell msbuild that the project should not generate any DLLs but to be instead only there to generate a nuspec the generated package would then instead not reference the other projects as packages (useful for using this target to make a metapackage with an always changing version number that cannot be commited as that would cause yet another version to be pushed).

A prime example is when doing CI builds using github actions, azure pipelines, etc and then using the build number to make preview builds (if it is not a tag build to be considered a release build), the same can be said for pre-release tags as well too.

See also: https://github.com/Elskom/Sdk/ it is in the non-main branch that the problem occurs.

**Comment by jeffkl** [comment] 2021-02-18 17:27
Help me understand the issue a little more, you're saying a NoTargets project which emits a package is missing dependencies from its NuGet package?  Like ProjectA, which emits PackageA, depends on ProjectB, which emits PackageB, and PackageA doesn't have a package dependency on PackageB?  Or is that not the issue?

**Comment by AraHaan** [comment] 2021-02-18 22:11
yes that is the issue exactly.

**Comment by jeffkl** [comment] 2021-02-24 20:29
I think this is currently by design.  Since a NoTargets project does not emit an assembly, it is considered to have no "runtime".  The runtime is generally a target framework like .NET Framework v4.8.  When a project reference is declared, NuGet and MSBuild validate that the runtimes for the two projects are compatible.  For example, a project that targets .NET Framework 3.5 cannot reference a project that references .NET Core 2.1.  This is because the runtime the finally assembly is loaded by won't be able to load both of them.

When building a NoTargets project, this compatibility check is disabled since there's no runtime for such a project to check against.

https://github.com/microsoft/MSBuildSdks/blob/a1bf27589ab57ef5bec483feea699026c5a90045/src/NoTargets/Sdk/Sdk.props#L37-L46

NoTargets projects are generally for copying files around or executing some other custom build logic.  We mostly recommend that they do not emit anything, like a package.

As you've stated, the only way to do this would be to create an actual CSPROJ project that uses Microsoft.NET.Sdk and set the `IncludeBuildOutput` property to `false`.

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target-inputs

This will create a package that contains everything else you've defined but leave the assembly from that project out of it.  Also, since NuGet will verify that the project is compatible with all of its project references, package dependencies will also be included.

**Comment by aaronla-ms** [comment] 2021-05-19 17:41
Seconded. My team has hit this issue as well, and didn't notice this limitation since, at present, our dependencies are PackageReferences, not ProjectReferences.

Also likely related: [dotnet/sdk/issues/16244: Feature Request: support for nuget package consumption in framework-less projects](https://github.com/dotnet/sdk/issues/16244)

**Comment by AraHaan** [comment] 2021-05-19 18:11
I agree it is related but when using the ``NoTargets`` Sdk which is the only difference I think.

**Comment by jeffkl** [comment] 2021-11-18 18:54
Closing in favor of https://github.com/dotnet/sdk/issues/16244

Since a NoTargets project doesn't really create anything runnable, its hard to say that packages created by them should have dependencies.

**Closed by jeffkl** 2021-11-18 18:54 UTC
Labels: wontfix

**Comment by aaronla-ms** [comment] 2021-12-01 18:12
> Since a NoTargets project doesn't really create anything runnable, its hard to say that packages created by them should have dependencies.

Well, it's not necessarily not runable. I regularly use NoTargets for any project type that doesn't have a good built-in msbuild support (e.g. a node.js executable project, or an msbuild props/targets only nugetpackage, sdk package, etc.). Those all have runnable code, and may have other package dependencies.

For an example of NoTargets used this way, see the [DotNet.ReproducibleBuilds.Isolated](https://github.com/dotnet/reproducible-builds/blob/main/src/DotNet.ReproducibleBuilds.Isolated/DotNet.ReproducibleBuilds.Isolated.csproj) package.

**Comment by aaronla-ms** [comment] 2021-12-01 18:16
> Closing in favor of [dotnet/sdk#16244](https://github.com/dotnet/sdk/issues/16244)

An excellent example of this is the [DotNet.ReproducibleBuilds.Isolated](https://github.com/dotnet/reproducible-builds/blob/main/src/DotNet.ReproducibleBuilds.Isolated/DotNet.ReproducibleBuilds.Isolated.csproj) nuget package.

> Since a NoTargets project doesn't really create anything runnable, its hard to say that packages created by them should have dependencies.

Msbuild targets/props can't have nuget dependencies? Or what about convenience ".All" packages that are used to bring in a big swath of dependencies via one convenient (but otherwise empty) dependency-only package? NoTargets would be a convenient way to create such packages.
