### ISSUE TITLE
cant add Microsoft.Build.CentralPackageVersions to directory.build.props

### ISSUE THREAD

**Issue by jmecosta** [microsoft/MSBuildSdks#99] opened 2019-05-31 09:32 UTC
hi,

would this be feasible?

```
D:\prod\structures\Test\TestTools\TestAdapters\FarmiAdapterTask\FarmiAdapterTask.fsproj : error  : Importing the file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Microsoft.Common.props" into the file "C:\Users\jocs\.nuget\packages\microsoft.build.centralpackageversions\2.0.36\Sdk\Sdk.props" results in a circular dependency.  C:\Users\jocs\.nuget\packages\microsoft.build.centralpackageversions\2.0.36\Sdk\Sdk.props

D:\prod\structures\Test\TestTools\TestAdapters\NunitTSServer\NunitTSServer.csproj : error  : Importing the file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Microsoft.Common.props" into the file "C:\Users\jocs\.nuget\packages\microsoft.build.centralpackageversions\2.0.36\Sdk\Sdk.props" results in a circular dependency.  C:\Users\jocs\.nuget\packages\microsoft.build.centralpackageversions\2.0.36\Sdk\Sdk.props

D:\prod\structures\Test\TestTools\TestAdapters\FarmiAdapterTask\FarmiAdapterTask.fsproj : error  : Importing the file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Microsoft.Common.props" into the file "C:\Users\jocs\.nuget\packages\microsoft.build.centralpackageversions\2.0.36\Sdk\Sdk.props" results in a circular dependency.  C:\Users\jocs\.nuget\packages\microsoft.build.centralpackageversions\2.0.36\Sdk\Sdk.props
```
So we dont need to import the sdk into all projects, so easier to maintain the centralpackageversions also

thanks

**Comment by jeffkl** [comment] 2019-05-31 15:20
You should be able to place this in your `Directory.Build.targets`:

```xml
 <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.36" />
```

I'm doing this in [one of my projects](https://github.com/jeffkl/SlnGen/blob/master/Directory.Build.targets#L18).  It doesn't work well in `Directory.Build.props` because it modifies `<PackageReference />` items which are declared after `Directory.Build.props` is imported.

**Comment by smaillet** [comment] 2019-06-02 13:51
@jeffkl That kinda sorta works - Specifically it works fine IFF ALL your projects are using PackageReference, however if you have any VCXPROJ in the tree for interop, that uses packages.config then you will break the build. As the included Sdk.props and Sdk.targets are not campaitble with anything that doesn't use PackageReference. Thus I'd recommend a tweak toe the Sdk.[props|targets] files to test for the PackageReferenceCapability and NOP the entire file if the project doesn't support that. (Unfortunately the MSBUILD Sdk element doesn't support a conditional and can't be placed within a Choose element)

**Comment by jeffkl** [comment] 2019-06-03 15:04
@smaillet I recently updated the logic to disable for projects that don't support PackageReference including `.vcxproj`, `.nuproj`, and `.ccproj`.  Its also disabled if there's a `packages.config` next to a project.  So that should make it possible to include an `<Sdk />` item in `Directory.Build.targets` for the whole tree.  Please file an issue if that's not the case for you when using the latest version.

**Comment by epvanhouten** [comment] 2019-06-18 14:42
I have a nuget.config that points all restores to happen out of a private authenticated feed of ***-AzureDevOps. This configuration works fine in master.

When adding `<Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.39" />` to my Directory.Build.targets a working Azure DevOps pipeline starts failing `dotnet restore` with 401 errors on the first project that it hits. All projects after that succeed in restoring with the authenticated devops feed.

Example failure log:

> Restoring packages for C:\Users\VssAdministrator\AppData\Local\Temp\5cfd4735-6bfc-42f6-9d63-5d9f09de09f5... 
> 0>D:\a\1\s\Directory.Build.targets : warning : Unable to load the service index for source https://pkgs.dev.azure.com/***/_packaging/***/nuget/v3/index.json. |  
> 0>D:\a\1\s\Directory.Build.targets : error : Unable to find package Microsoft.Build.CentralPackageVersions. No packages exist with this id in source(s): ***-AzureDevOps

Content of Directory.Build.targets:
    <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
        <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.39" />
    </Project>

**Comment by MeikTranel** [comment] 2019-07-31 19:06
@epvanhouten what sdk-version are you running your builds with?

There used to be some issues with MSBuild's nuget based sdk resolution, wherein the Sdk would be downloaded but the build fails - and only after the second dotnet build it actually worked.

**Comment by epvanhouten** [comment] 2019-08-01 13:04
@MeikTranel I updated to 2.0.46 and that seemed to get me past the restore problem.

However, we are using NSwag.MSBuild v11.17.21 which defines properties to be used in the project files. When using the Directory.Build.targets file to apply the SDK these properties are not initialized. Since I can't use the SDK in the props file I don't see much of a way forward.

**Comment by jeffkl** [comment] 2019-08-01 16:29
In Azure DevOps hosted builds where you need authentication, you'll need to configure the [Azure Artifacts Credential Provider](https://github.com/Microsoft/artifacts-credprovider#azure-artifacts-credential-provider) otherwise restore will fail with authentication errors (401).

**Comment by jeffkl** [comment] 2019-08-01 16:30
I'm closing this issue as the root cause was central package versioning was incorrectly being enabled VCXPROJ which was fixed.

**Closed by jeffkl** 2019-08-01 16:30 UTC
